"""initial migtration

Revision ID: a3bb669b46b2
Revises: 
Create Date: 2023-10-12 13:29:54.168737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bb669b46b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenditures_name'), ['name'], unique=True)

    op.create_table('incomes',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incomes_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incomes_name'))

    op.drop_table('incomes')
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenditures_name'))

    op.drop_table('expenditures')
    # ### end Alembic commands ###
